apiVersion: apps/v1 
kind: Deployment 
metadata: 
    name: sampleapp-deployment 
    labels: 
      app: sampleapp 
 spec: 
   replicas: 3 
     template: 
       metadata: 
         name: sampleapp 
         labels: 
           app: sampleapp 
       spec: 
         containers: 
         - name: sampleapp 
           image: sampleappacr.azurecr.io/sampleapp:v1 
           imagePullPolicy: IfNotPresent 
         restartPolicy: Always 
     selector: 
       matchLabels: 
         app: letskube 
 
--- 
 
 apiVersion: v1 
 kind: Service 
 metadata: 
  name: sampleapp-service 
spec: 
  selector: 
    app: sampleapp 
  ports: 
   - port: 80 
  type: LoadBalancer